#!/bin/bash


touch test_file1

file1="./test_file1"
file2="./test_file2"


if [ -e "$file1" ]; then
	echo "file 1 exists"
else
	echo "file 1 dose not exists"
fi

if [ -r "$file1" ]; then
	echo "$file1 is readable"
fi
		
if [ -w "$file1" ]; then
	echo "$file1 is writable"
fi
		
if [ -x "$file1" ]; then
	echo "$file1 is executable"
fi
		
if [ -d "$file1" ]; then
	echo "$file1 is a directory"
fi
		
if [ -L "$file1" ]; then
	echo "$file1 is a symbolic link"
fi
		
if [ -p "$file1" ]; then
	echo "$file1 is a named pipe"
fi
		
if [ -S "$file1" ]; then
	echo "$file1 is a network socket"
fi

if [ -G "$file1" ]; then
	echo "$file1 is owned by the group"
fi
		
if [ -O "$file1" ]; then
	echo "$file1 is owned by the userid"
fi
