#!/bin/bash

num=1

while [ $num -le 100 ]; do
	echo "num is : $num"
	num=$(( num + 1 ))
done


num=1

while [ $num -le 20 ]; do
  if (( ((num%2)) == 0 )); then
	echo "$num is even number"
	num=$((num+1))
	continue	  
  fi

  if ((num >= 15)); then
	break
  fi
	
	echo "number is $num"
	num=$((num+1))
done	
	
	
