#!/bin/bash


#---------for loop---


for (( i=0; i<=19; i=i+1 )); do
	
	echo $i
done

for i in {A..Z}; do
	echo $i
done



num=1

until [ $num -ge 20 ]; do
	echo "num is : $num"
	num=$((num+2))
done


#--------------------------------
num=1

while [ $num -le 100 ]; do
	echo "num is : $num"
	num=$(( num + 1 ))
done


num=1

while [ $num -le 20 ]; do
  if (( ((num%2)) == 0 )); then
	echo "$num is even number"
	num=$((num+1))
	continue	  
  fi

  if ((num >= 15)); then
	break
  fi
	
	echo "number is $num"
	num=$((num+1))
done	
	
	
